name: Deploy to VPS

on:
  push:
    branches:
      - Updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: Updated

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and deploy
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << 'EOF'
        cd ~
        rm -rf faired
        git config --global user.email "yashoswal18@gmail.com"
        git config --global user.name "mergebot"
        git clone --branch Updated https://github.com/Itzmepapa123/faired.git
        cd faired
        git fetch origin
        git checkout Updated
        git pull origin Updated
        docker build -t fair:latest .
        docker stop fair || true
        docker rm fair || true
        docker run -d --name fair -p 2273:2273 fair:latest
        EOF
